Vista Promocion Protectores Bucales y Acetatos
AleRojas27/login_cursodontic pull request #3
Opened 2023-05-13 03:06 UTC by AleRojas27

Aqui esta mi idea de la vista para la promocion del curso de Protectores Bucales y los Acetatos.

2023-05-13 03:28 UTC, racunas requested changes
1. Las imágenes debes de obtenerlas desde una URL, no importarlas directamente en el proyecto. Esto es porque al momento de hacer la integración en producción se hace con las URL de las imagenes.

2. A la vista le hacen falta varios elementos que no están y son importantes. Cuando diseñes una vista, ponte en los zapatos del cliente y pregúntate todo lo que cualquier cliente haría.
Elementos que considero hacen falta:

- Descripción del curso y paquete de acetatos
- Descripción de la oferta
- Contenido del curso
- Vídeo de presentación del curso
- Reseñas
- Tiempo de envío de los acetatos
- Preguntas frecuentes
- Métodos de pago

Para comenzar a pivotear el diseño, la vista debe tener al menos los elementos mencionados anteriormente. Por favor completarlo para que la siguiente semana trabajemos sobre ello.

2023-05-18 10:45 UTC, AleRojas27 commented
Se agregaron los detalles faltantes, solo hicieron falta las reseñas y las preguntas frecuentes

2023-05-23 05:11 UTC, racunas commented
Se ve más completo, la retroalimentación que te puedo dar en este momento es:

- El botón de "Comprar ahora" deberá estar siempre pegado al bottom de la pantalla, sobrepuesto encima del contenido, para que siempre pueda darse clic estando en cualquier parte de la página. Ahí mismo puede mostrarse el precio del paquete y el botón de comprar, adjunto un ejemplo de lo que me refiero.

![Captura de Pantalla 2023-05-22 a la(s) 23 09 49](https://github.com/AleRojas27/login_cursodontic/assets/41505736/5f6d9970-25c3-4882-9858-230b52acedb2)

- Puedes basarte también en ejemplos que te compartí en Slack, de algunas páginas web bien diseñadas, puedes copiar su diseño.

2023-05-23 05:11 UTC, merged

2023-05-23 05:12 UTC, racunas reviewed
LGTM++